name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install package
      run: |
        sudo apt-get install ninja-build libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libboost-dev libcurl4-openssl-dev libgtk-3-dev libgif-dev libglu1-mesa-dev libharfbuzz-dev libmpg123-dev libopencv-dev libopus-dev libopusfile-dev libsoundtouch-dev libswresample-dev libtiff-dev libturbojpeg0-dev libvorbis-dev libwebp-dev libxft-dev uuid-dev xorg-dev

    - name: Checkout Siv3D
      uses: actions/checkout@v3
      with:
        repository: Siv3D/OpenSiv3D
        path: Siv3D

    - name: Setup Siv3D
      working-directory: Siv3D/Linux
      run: |
        cmake -B build -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo .
        cmake --build build
        sudo cmake --install build

    - name: Configure Dot Screen Saver
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release .

    - name: Build Dot Screen Saver
      run: |
        cmake --build build

  windows:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Siv3D
      run: |
        curl -OL https://siv3d.jp/downloads/Siv3D/manual/0.6.10/OpenSiv3D_SDK_0.6.10.zip
        Expand-Archive -Path OpenSiv3D_SDK_0.6.10.zip  -DestinationPath .

    - name: Configure Dot Screen Saver
      env:
        SIV3D_0_6_10: ${{ github.workspace }}/OpenSiv3D_SDK_0.6.10
      run: |
        cmake -B build .

    - name: Build Dot Screen Saver
      env:
        SIV3D_0_6_10: ${{ github.workspace }}/OpenSiv3D_SDK_0.6.10
      run: |
        cmake --build build --config Release
